### ISSUE TITLE
New Garaxpert process does not work

### ISSUE THREAD

**Issue by Sem1ot1c** [DeepSkyForge/GraXpert4PixInsight#1]
When I tey to launch the new GraXpert process I get this
<img width="314" alt="Screenshot 2024-04-22 225007" src="https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/46023553/87aa39bb-4da9-4b8c-aa25-7f69d4e5d666">

**Comment by sjames28** [comment]
I have the same issue.  I tried uninstalling and old and new versions of Graxpert and reinstalling but the above error persists.

**Comment by Sem1ot1c** [comment]
The solution seems to be to run the native version of GraXpert (not from Pixinsight) when you get the prompt to download the AI model for both Graxpert and the denoise. Then it runs fine from inside Pixinsight.

Memo to self: Read the instructions fully first!Haha!

**Comment by DeepSkyForge** [comment]
Sorry for delay, I was on travel.
This is a known issue in GraXpert.

To fix that, you have to:

1. manually remove old AI models (see locations below),
2. Run GraXpert application and process an image (background extraction and denoising) to force AI model download.

My Quick Start Guide gives location of AI models but in short:

- Windows: C:\Users\<NAME>\AppData\Local\GraXpert\GraXpert\ai-models\
- macOS: /Users/<NAME>/Library/Application Support/GraXpert/ai-models/
- Linux: /home/<NAME>/.local/share/GraXpert/ai-models/

Let me know if you need more help.

**Comment by Sem1ot1c** [comment]
Many thanks for this, I should have read the instructions more fully, or even at all.  My fault.

Regards

Peter (Haveland)

**Comment by DeepSkyForge** [comment]
Thanks for your feedback. I close the issue :-)
