### ISSUE TITLE
Unable to download repository information

### ISSUE THREAD

**Issue by spigolonrenzo** [DeepSkyForge/GraXpert4PixInsight#14]
https://pixinsight.deepskyforge.com/update/graxpert-process/: Parsing repository update information: Parsing Signature element (line=1 offset=0): Unknown code signing identity 'JoelVallier'.

I have this error

**Comment by DeepSkyForge** [comment]
Hi,

Your PixInsight version do not recognize my Certified PixInsight Developer ID.
Please ensure you have PixInsight 1.8.9-2 build 1597 or higher.

You can check version from PixInsight menu RESOURCES > About PixInsight...
You can download last version from https://pixinsight.com/dist/index.html
Current version is 1.8.9-2 build 1605

After upgrade, command "lscpd" in PixInsight console should display my certificate and you should be able to install GraXpert Process.

Good to know: Check Updates from PixInsight checks only scripts and process versions.
It doesn't check PixInsight version itself.

Regards
