### ISSUE TITLE
Unable to start GraXpert process from Pixinsght

### ISSUE THREAD

**Issue by Pirol20xx** [DeepSkyForge/GraXpert4PixInsight#16]
I am not able to start GraXpert process from Pixinsight (1.8.9 - 2, build 1597) . I am using MacOS on an Intel processor. I have installed GraXpert 3.0. GraXpert works well when used directly as a program (AI models are downloaded). I did install Graxpert process for Pixinsight as recommended. I can start Pixinsight as usual and also I can load a .fits file (directly after WBPP). When trying to run GraXpert process I find the icons under Script-Toolbox-GraXpert and Script-Toolbox-GraXpertDenoise. When using one of these two  icons I receive the following error message in the Pixinsight process window:

run --execute-mode=auto "/Applications/PixInsight/src/scripts/Toolbox/Graxpert.js"

Processing script file: /Applications/PixInsight/src/scripts/Toolbox/Graxpert.js
*** Error: Signature verification failed for 'GraXpert': Invalid code signature: /Applications/PixInsight/src/scripts/Toolbox/Graxpert.js

Any help is highly appreciated.

**Comment by DeepSkyForge** [comment]
Sorry, this script is part of Toolbox from https://www.ideviceapps.de/graxpert-script.html
I provide support only for GraXpert Process in PixInsight.

Process was introduced in official video GraXPert 3.0: https://www.youtube.com/watch?v=ZDqvIn5Vnig
You can get it from https://www.deepskyforge.com/index.html

GraXpert Process is compatible with PixInsight 1.8.9-2 build 1597 so it should be ok.
In any case, if you decide to move to process, I'll be happy to support you in case of problem.

Regards

**Comment by DeepSkyForge** [comment]
I did not mentionned but if you have installed GraXpert process (not the script from Toolbox) 
you'll find GaXpert process in menu PROCESS => \<Etc\> => GraXpert.
Signature will be accepted.
Please cofirm.
