### ISSUE TITLE
Does not work under linux due to lowercase executable search

### ISSUE THREAD

**Issue by andreya108** [DeepSkyForge/GraXpert4PixInsight#20]
GraXpert PI process does not work under linux.
Investigation revealed it looks for lowercase executable 'graxpert' in PATH, but it actually named 'GraXpert', so it fails.

```
statx(AT_FDCWD, "/usr/local/sbin/graxpert", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffc7adfb880) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/local/bin/graxpert", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffc7adfb880) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/sbin/graxpert", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffc7adfb880) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/bin/graxpert", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffc7adfb880) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/sbin/graxpert", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffc7adfb880) = -1 ENOENT (No such file or directory)
```
Why have you not added executable selection settings?

**Comment by DeepSkyForge** [comment]
Hi,

On Windows and macOS it's no more required to configure path.
Install process ensure application can be called from command line.

On Linux, I suggest to create a symbolic link to the application with below command:
sudo ln -s /opt/GraXpert/GraXpert /usr/bin/graxpert
Assuming here that application is installed in /opt/GraXpert/.

Regards,

Joël

**Comment by andreya108** [comment]
Yes, symlink solution is obvious and it is the first thing I've done after discovering why plugin is not working.

The problem is that it is not clear for user what to do. There is nothing about in docs, no configuration available to select GraXpert executable (while script version does).

**Comment by DeepSkyForge** [comment]
It is mentionned in Quick Start Guide, in page Technical Information Linux Platform
https://www.deepskyforge.com/documents/GraXpertProcess4PixInsight-EN.pdf

A link to the documentation is provided on my web page
https://www.deepskyforge.com/index.html

I should maybe capture error and display an explicit message.
I'll implement this in next release.
