### ISSUE TITLE
GraXpert process missing in PI

### ISSUE THREAD

**Issue by chvvkumar** [DeepSkyForge/GraXpert4PixInsight#24]
Issue:
Followed steps from the following URL to install GraXpert PI Process, verified iti s indeed installed from PI's Installed Updates screen (screenshot attached) but the Process does not show up under Process > Etc. 

I am running the following versions
PI: 1.8.9-2 Build 1601
GraXpert: 3.0.2
OS: Windows 11 Pro

Things I have checked:
1. I can open GraXpert standalone
2. I can invoke GraXpert from command line (so the paths are correct)
3. I have removed the toolbox repo and then restarted PI to finish uninstall, reset updates and reinstalled all updates again.

https://www.deepskyforge.com/index.html

![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/16548147/06c44ce1-751a-4742-8bc3-3ce4464349f9)

![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/16548147/7610713b-8844-4a5d-ba95-eac81eed184b)

![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/16548147/6502598b-4106-4783-a9b0-d3824cde0ab1)

Pixinsight Console on startup:

```
Initializing PixInsight...

JavaScript runtime initialized.

Installing 61 module(s):
C:/Program Files/PixInsight/bin/Annotation-pxm.dll
C:/Program Files/PixInsight/bin/APASS-pxm.dll
C:/Program Files/PixInsight/bin/ArcsinhStretch-pxm.dll
C:/Program Files/PixInsight/bin/AssistedColorCalibration-pxm.dll
C:/Program Files/PixInsight/bin/BackgroundModelization-pxm.dll
C:/Program Files/PixInsight/bin/Blink-pxm.dll
C:/Program Files/PixInsight/bin/BMP-pxm.dll
C:/Program Files/PixInsight/bin/CloneStamp-pxm.dll
C:/Program Files/PixInsight/bin/ColorCalibration-pxm.dll
C:/Program Files/PixInsight/bin/ColorManagement-pxm.dll
C:/Program Files/PixInsight/bin/ColorSpaces-pxm.dll
C:/Program Files/PixInsight/bin/CometAlignment-pxm.dll
C:/Program Files/PixInsight/bin/Compatibility-pxm.dll
C:/Program Files/PixInsight/bin/Convolution-pxm.dll
C:/Program Files/PixInsight/bin/CosmeticCorrection-pxm.dll
C:/Program Files/PixInsight/bin/Debayer-pxm.dll
C:/Program Files/PixInsight/bin/Deconvolution-pxm.dll
C:/Program Files/PixInsight/bin/EphemerisGeneration-pxm.dll
C:/Program Files/PixInsight/bin/FastIntegration-pxm.dll
C:/Program Files/PixInsight/bin/FilterManager-pxm.dll
C:/Program Files/PixInsight/bin/FindingChart-pxm.dll
C:/Program Files/PixInsight/bin/FITS-pxm.dll
C:/Program Files/PixInsight/bin/Flux-pxm.dll
C:/Program Files/PixInsight/bin/Fourier-pxm.dll
C:/Program Files/PixInsight/bin/Gaia-pxm.dll
C:/Program Files/PixInsight/bin/Geometry-pxm.dll
C:/Program Files/PixInsight/bin/Global-pxm.dll
C:/Program Files/PixInsight/bin/GradientCorrection-pxm.dll
C:/Program Files/PixInsight/bin/GradientDomain-pxm.dll
C:/Program Files/PixInsight/bin/GREYCstoration-pxm.dll
C:/Program Files/PixInsight/bin/Image-pxm.dll
C:/Program Files/PixInsight/bin/ImageCalibration-pxm.dll
C:/Program Files/PixInsight/bin/ImageIntegration-pxm.dll
C:/Program Files/PixInsight/bin/ImageRegistration-pxm.dll
C:/Program Files/PixInsight/bin/INDIClient-pxm.dll
C:/Program Files/PixInsight/bin/IntensityTransformations-pxm.dll
C:/Program Files/PixInsight/bin/JPEG-pxm.dll
C:/Program Files/PixInsight/bin/JPEG2000-pxm.dll
C:/Program Files/PixInsight/bin/LocalHistogramEqualization-pxm.dll
C:/Program Files/PixInsight/bin/MaskGeneration-pxm.dll
C:/Program Files/PixInsight/bin/Morphology-pxm.dll
C:/Program Files/PixInsight/bin/MultiscaleProcessing-pxm.dll
C:/Program Files/PixInsight/bin/NetworkService-pxm.dll
C:/Program Files/PixInsight/bin/NoiseGeneration-pxm.dll
C:/Program Files/PixInsight/bin/NoiseReduction-pxm.dll
C:/Program Files/PixInsight/bin/NoOperation-pxm.dll
C:/Program Files/PixInsight/bin/Obsolete-pxm.dll
C:/Program Files/PixInsight/bin/PixelMath-pxm.dll
C:/Program Files/PixInsight/bin/RAW-pxm.dll
C:/Program Files/PixInsight/bin/RestorationFilters-pxm.dll
C:/Program Files/PixInsight/bin/Sandbox-pxm.dll
C:/Program Files/PixInsight/bin/SplitCFA-pxm.dll
C:/Program Files/PixInsight/bin/SubframeSelector-pxm.dll
C:/Program Files/PixInsight/bin/TGV-pxm.dll
C:/Program Files/PixInsight/bin/TIFF-pxm.dll
C:/Program Files/PixInsight/bin/XISF-pxm.dll
C:/Program Files/PixInsight/bin/BlurXTerminator-pxm.dll
C:/Program Files/PixInsight/bin/GeneralizedHyperbolicStretch-pxm.dll
C:/Program Files/PixInsight/bin/NarrowbandNormalization-pxm.dll
C:/Program Files/PixInsight/bin/NoiseXTerminator-pxm.dll
C:/Program Files/PixInsight/bin/StarXTerminator-pxm.dll
* Scripting resources updated.
61 of 61 module(s) installed.

Running initialization scripts...

Processing script file: C:/Program Files/PixInsight/etc/init.pjsr/pjsr-core-defs.js


Running startup scripts...

Processing script file: C:/Program Files/PixInsight/etc/startup/startup.scp

_____________       ________            _____        ______ _____
___  __ \__(_)___  _____  _/_______________(_)______ ___  /___  /_
__  /_/ /_  /__  |/_/__  /__  __ \_  ___/_  /__  __ `/_  __ \  __/
_  ____/_  / __>  < __/ / _  / / /(__  )_  / _  /_/ /_  / / / /_
/_/     /_/  /_/|_| /___/ /_/ /_//____/ /_/  _\__, / /_/ /_/\__/
                                             /____/

PixInsight Core 1.8.9-2 Ripley (x64) (build 1601 | 2024-03-01)
Copyright (c) 2003-2024 Pleiades Astrophoto
----------------------------------------------------------------------
Welcome to PixInsight. Started 2024-05-05T20:51:45.626Z

* Parallel processing enabled: Using 24 logical processors.
* WebView: Using raster-only graphics.

open "G:/Astrophotography/Pixinsight Projects/Mono.pxiproject/project.xosm"
Opening 1 file(s):

Loading project:
G:/Astrophotography/Pixinsight Projects/Mono.pxiproject/project.xosm
* Project integrity verified, SHA1 checksum = 24e0e3fcd5633a3e9cde3caf54df1709d766bfcd
* Reading project metadata
Creation date ............... 2024-03-10T17:08:07.173Z
Core version ................ 1.8.9-2
Author ...................... <* undefined *>
Project description ......... <* undefined *>
Project generation features:
XOSM version ................ 1.1
Include images .............. true
Include previews ............ true
Include view properties ..... true
Include interface states .... true
Only open interfaces ........ true
Include icons ............... true
Include text documents ...... true
Include thumbnail ........... true
Include all workspaces ...... true
Include documentation ....... false
File checksums (SHA1) ....... true
Bundled project ............. true
Sealed project .............. true
Purge existing files ........ false
Check space available ....... true
Incremental writing ......... true
Offline storage threshold ... 4.000 KiB
Block compression ........... lz4hc+sh
Workspaces .................. Workspace01 Workspace02 Workspace03 Workspace04 Linear_Post_Processing
Screen geometry ............. w=2560 h=1440
* Loading interface states
* Loading embedded XPSM
Reading icon: STF
Reading icon: WBPP
Reading icon: WBPP_Flats
Reading icon: DBE
Reading icon: AutomaticBackgroundExtractor
Reading icon: GraXPert
Reading icon: GradientCorrection
Reading icon: SPCC_RGB
Reading icon: SPCC_SHO
Reading icon: Crop
Reading icon: SCNR
Reading icon: LRGBCombination
Reading icon: LRGBCombination_RGBStars
Reading icon: AddHaToRGB
Reading icon: Histogram
Reading icon: ImageSolver
Reading icon: MosaicByCoordinates
Reading icon: GradientMergeMosaic
Reading icon: StarReductionMethod2_V3
Reading icon: StarReductionMethod3_V3
Reading icon: NarrowbandNormalization
Reading icon: Bills_Stretch_Llinked__V6
Reading icon: Bills_Stretch_Unlinked_V6
Reading icon: BlurXTerminator
Reading icon: StarXterminator
Reading icon: NoiseXTerminator
Reading icon: Curves
Reading icon: CloneForStarless
Reading icon: PixelMath
Reading icon: StarReductionMethod1_V3
* Regenerating masking relations
* Updating workspaces
* Project loaded successfully.
548.500 ms

```

**Comment by DeepSkyForge** [comment]
Hello,

You did all thinks I could suggest...
Startup logs shows clearly the GraXpert process is not loaded.
This happen when module failed to load, PixInsight disable it and the only possibility is to reset updates and install again but you already did it.

Did you restarted PixInsight after reset update?
Do you have GraXpert-pxm.dll and GraXpert-pxm.xsgn in C:\Program Files\PixInsight\bin.
I see in logs a process icon "Reading icon: GraXPert", is it the script from Toolbox?

Could you install last PixInsight build 1605 ?
Reset all updates if not done during install and restart PixInsight.
When PixInsight list all modules and script to upload, select only GraXpert.
After restart, check startup logs and copy/save install logs.
Check if GraXpert is in Process/Etc menu.
If no send me install and startup logs and check again content of C:\Program Files\PixInsight\bin.
During all tests start PixInsigh application, do not start PixInsight by loading a project.
If you load a project, remove GraXpert process icon.

I hope this will help.
Let me know.

**Comment by DeepSkyForge** [comment]
No news but I prefer to keep this issue open for the moment.
Indeed, nobody else reported this issue and I'm curious to know the end story.

**Comment by chvvkumar** [comment]
> No news but I prefer to keep this issue open for the moment. Indeed, nobody else reported this issue and I'm curious to know the end story.

Sorry for the late reply, we were dealing with work and extreme weather. I have not dug deep into it yet but I will keep you updated.


`Did you restarted PixInsight after reset update?`
I did restart both my PC and PI multiple times after resetting the PI updates.

`Do you have GraXpert-pxm.dll and GraXpert-pxm.xsgn in C:\Program Files\PixInsight\bin.`
I see the files in PI's bin folder
![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/16548147/6fde5010-bf50-41ff-8199-eab5f0584557)

`I see in logs a process icon "Reading icon: GraXPert", is it the script from Toolbox?`
You are correct, this is from the Toolbox and I forgot to delete the ProcessIcon from my saved project.

```
Could you install last PixInsight build 1605 ?
Reset all updates if not done during install and restart PixInsight.
When PixInsight list all modules and script to upload, select only GraXpert.
After restart, check startup logs and copy/save install logs.
Check if GraXpert is in Process/Etc menu.
If no send me install and startup logs and check again content of C:\Program Files\PixInsight\bin.
During all tests start PixInsigh application, do not start PixInsight by loading a project.
If you load a project, remove GraXpert process icon.
```
I will try these this weekend and will get back to you.

Thank you for your time!

**Comment by chvvkumar** [comment]
Actually, I managed to solve it!

I copied the two files you mentioned to a different folder from `C:\Program Files\PixInsight\bin`. Then I went to Process > Modules >Install Modules, selected this new folder location and did a search. PI found the module and I then installed it. The entry shows up now!

![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/16548147/27eb3b2c-264e-4cb7-ad5c-f64a67df6d77)

**Comment by DeepSkyForge** [comment]
Thanks @chvvkumar for your feedback.
This shows that GraXpert process itself works.
I'm suspecting a problem in module loading after automatic installation.
If something fail during loading, PixInsight "disable" module till next update.
Usually, a reset update fix the issue but you already did it.

Please take care, when I'll release an update, PixInsight will raise an error saying that another instance of GraXpert already exists (the one you have installed manually inti a different location).
Before update, you should manually uninstall current instance (menu PROCESS > Modules > Manage Modules and disable GraXpert).

I noticed that you have PixInsight build 1601.
You should upgrade to last 1605.
This will reset all script/module updates and normally you should have at the end GraXpert properly installed.

I keep this issue open.

**Comment by chvvkumar** [comment]
Thank you for all your work, @DeepSkyForge 

For some reason my PI update is not showing build 1605 in my updates but I will get my install updated.

**Comment by DeepSkyForge** [comment]
Just for your information, check update shows only scripts and modules updates, never PixInsight updates.
For PixInsight update you have to go to https://pixinsight.com/dist/index.html and get last 1.8.9-2 build.
Last build are annouced here: https://pixinsight.com/forum/index.php?forums/announcements.4/
That the only possibility to get informed about updates.

**Comment by chvvkumar** [comment]
> Just for your information, check update shows only scripts and modules updates, never PixInsight updates. For PixInsight update you have to go to https://pixinsight.com/dist/index.html and get last 1.8.9-2 build. Last build are annouced here: https://pixinsight.com/forum/index.php?forums/announcements.4/ That the only possibility to get informed about updates.

Got PI updated and I am happy to report that the GraXpert process is still there and working just fine after the update.
