### ISSUE TITLE
GraXpert cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by bobbryant** [DeepSkyForge/GraXpert4PixInsight#25]
I installed GraXpert v3.0.2 into windows 10.  GraXpert executes from windows but when I execute it from PixInsight (PI) I get a cx)Freeze: Python error in the main script.
![GraXpert Error](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/6720057/29e6ea3b-dfcd-4475-92ed-d45f2d523e11)

Also, I cannot remove the process or script lengths for GraXpert from PI.

**Comment by DeepSkyForge** [comment]
Hi,
This is a known issue in GraXpert (not in PxInsight process).
See my response here: https://github.com/DeepSkyForge/GraXpert4PixInsight/issues/1#issuecomment-2075829780
Regards,
Joël

**Comment by bobbryant** [comment]
Thanks, that fixed the problem.
