### ISSUE TITLE
Error installing PixInsight

### ISSUE THREAD

**Issue by gustavosbcarvalho** [DeepSkyForge/GraXpert4PixInsight#27]
I'm trying to install GraXpert on my PixInsight and I'm not succeeding. An error message appears right after I add the repository information and search for Update.

Parsing Sgnature element (line=1 offset=0) Unknow code signing identity 'JoelVallier'

![unnamed](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/134982238/4afc1df8-5f07-47f9-802c-b8fd506ef976)

**Comment by DeepSkyForge** [comment]
Your PixInsight version is too old.
Please check my answer here: https://github.com/DeepSkyForge/GraXpert4PixInsight/issues/14#issuecomment-2080175944
Regards
