### ISSUE TITLE
Update to GraXpert 3, Missing AI

### ISSUE THREAD

**Issue by Altair8861** [DeepSkyForge/GraXpert4PixInsight#28]
I installed the 3.0 GraXpert on Mac OS. GraXpert now appears under my Process menu.

However, it does not find the AI file(s).

Where do I download this how how do I point to it?

**Comment by Altair8861** [comment]
Problem solved, read the directions ;-)

**Comment by DeepSkyForge** [comment]
Perfect! I can close the issue :-)

**Comment by DeepSkyForge** [comment]
For your information, if there is no AI model installed, the process will launch GraXpert and GraXpert will download last version.
This takes time and if you stop the process during download, you'll have to remove manually unterminated downloaded file(s).
User guide gives technical information related to file location (https://www.deepskyforge.com/documents/GraXpertProcess4PixInsight-EN.pdf).
Currently GraXpert do not give information to PixInsight about download progress.
So, it's better to launch the AI model download from GraXpert application.
Indeed, from Application you know exactly when AI model is downloading and when image is processed.
