### ISSUE TITLE
Graxpert 3.X in Pixinsight

### ISSUE THREAD

**Issue by wolfgangstrasser55** [DeepSkyForge/GraXpert4PixInsight#29]
After the installation I get the following error message, as can I do, I reset the updates, downloaded new updates but nothing changes.
C:/Program Files/PixInsight/bin/GraXpert-pxm.dll
<* failed *>
*** PixInsight API Error: Module: C:/Program Files/PixInsight/bin/GraXpert-pxm.dll: Unsupported API version 180 (expected = 179).: Module load error

Thanks for the help

**Comment by AstroDeepSky** [comment]
Are you using Process or Toolbox script ?
What is your PixInsigth version ?
Process requires PixInsight 1.8.9-2 build 1597 or higher.
Refer https://github.com/DeepSkyForge/GraXpert4PixInsight/wiki/Unknow-code-signing-identity

**Comment by wolfgangstrasser55** [comment]
sorry, I just reinstalled pixinsight, it works now.

**Comment by DeepSkyForge** [comment]
Good!
