### ISSUE TITLE
Freeze Python Error

### ISSUE THREAD

**Issue by Bramble12** [DeepSkyForge/GraXpert4PixInsight#31]
I know this has been raised before, but I have this problem and I have attempted the solutions described without success. I had been using Graxpert very happily until I tried to improve it with the update!

I have loaded Graxpert as a Process and believe I have deleted all old data.  When  running the program from Pixinsight I get the Freeze Python Error.  I have looked into the folder where the the link is supposed to be and it is empty.  I have used GX as standalone. I suppose this forced the AI model to load, and the task is performed correctly.  So, where is the program? Can you offer any help as I am going around in circles trying to fix this.  I am not a computer geek, so simple explanations are best for me.

**Comment by DeepSkyForge** [comment]
Hello,

I'll try to help you.
Some basic question to start:
1. What's your operating system? Windows 10, Windows 11, MacOS, Linux ?
2. How do you launch GraXpert from PixInsight ? SCRIPT > Toolbox > GraXpert or PROCESS > Etc > GraXpert or other menu ?
3. What are messages displayed in PixInsight console ?
4. Could indicate last sentence in error message ? Is it a problem with file, or module, or something else ?

You can try to uninstall _ALL_ versions of GraXpert applications and install again.

**Comment by DeepSkyForge** [comment]
Any news?

**Comment by Bramble12** [comment]
HiReally sorry - I meant to reply and thank you for your kind attention!
I have found the solution to the problem.  I did get Graxpert loaded into PI and it was visible as a process.  Initially, it would not work, except for the de-noise program.  I realised that I had not, in fact, forced the download of the gradient removal tool. Possibly this is because these two actions require looking into different sides of the Graxpert standalone programme and each has to be ‘forced’ separately.
Anyway, I got there and all seems to be resolved.
Thanks again for getting back to me.
Sarah.


Sent from Yahoo Mail for iPad


On Monday, May 27, 2024, 6:33 PM, DeepSkyForge ***@***.***> wrote:




Any news?

**Comment by DeepSkyForge** [comment]
Thank you very much for your feedback.
Yes, you have on one side the GraXpert standalone application and on the other side the process in PixInsight.
When a new AI version is avaible you have to download it from Application before using it in PixInsight.
You can also check periodicly is new version of the application is released.
Process is updated separatly as any other process or script in PixInsight.
