### ISSUE TITLE
Graxpert DeNoise Will Not Run in Pixinsight

### ISSUE THREAD

**Issue by Rgrenader** [DeepSkyForge/GraXpert4PixInsight#32]
My Pixinsight installation is current.  When I add the Graxpert repository and go through the convoluted upgrade process, reastrt the program and run Graxpert as a process, the DeNoise function stops with numerous errors (screenshot attached).  Background Extraction runs without error. 
![Screenshot 2024-05-26 113234](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/170886449/e25af01d-b3c0-465a-aab8-293fe27181ed)

**Comment by DeepSkyForge** [comment]
Hi,

I just saw your comment on View into Space and jumped here :-)
Could you please ensure you have GraXpert application version 3.0.2.

After update, denoise an image with the application to download last AI model.
Then you will see AI version in process dopdown list and it should work.

I let you confirm.

**Comment by Rgrenader** [comment]
Thank You! That did it.  I just have to remember the steps for the next upgrade.  

 

Thank you for your immediate response.

**Comment by DeepSkyForge** [comment]
Thanks for the confirmation.
