### ISSUE TITLE
Pixinsight update causes signature verification to fail.

### ISSUE THREAD

**Issue by fergy-nz** [DeepSkyForge/GraXpert4PixInsight#33]
Updated PixInsight this morning to 1.8.9-3
Have checked for updates in PI
When I attempt to run GraXpert I get the following:
```
Processing script file: C:/Program Files/PixInsight/src/scripts/Toolbox/Graxpert.js
*** Error: Signature verification failed for 'GraXpert': Invalid code signature: C:/Program Files/PixInsight/src/scripts/Toolbox/Graxpert.js
```
Possibly related to this: [https://pixinsight.com/forum/index.php?threads/module-signatures-required.23219/]()

**Comment by DeepSkyForge** [comment]
Hi,

No, this is not related to the post from Juan in PixInsight forum.
PixInsight did not put yet this in there last version.

In fact, you are using the **Toolbox Script** developped by Jürgen (https://www.ideviceapps.de/pixinsight-toolbox.html).
The problem you report is a known issue and happen when PixInsight release a new version.

I'm the developper of the GraXpert **Process** (not Script) described here: https://www.deepskyforge.com/.
I tested the process on Windows 11 yesterday with PixInsight 1.8.9-3 and it works fine.

I suggest you to migrate to the process that was officially communicated by GraXpert team when they released GraXpert 3.0 (https://www.youtube.com/watch?v=ZDqvIn5Vnig).

Process is properly signed and so should not be affected by future change announced by Juan.
This is visible when you install the process: a green star is displayed on the left of GraXpert module during PixInsight boot:
![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/157253452/c9baba64-d1ce-4bcb-9e6f-e2d486b0c0e1)

I close this issue later (probably other people will come here for same issue).
Do not hesitate to open a new case if you have some difficulties with the process.

**Comment by fergy-nz** [comment]
Thank you

**Comment by hanosteyn** [comment]
Thank you
