### ISSUE TITLE
Signature Unavailable Error

### ISSUE THREAD

**Issue by Nagant132017** [DeepSkyForge/GraXpert4PixInsight#34]
Hi,
I have recently updated my pixinsight to version 1.8.9-3.
After update the pixinsight, when I check for updates, I could see the information of script like below and the script installation does not work.
What could I do to fix this error?
(Sorry, I was trying to add image but git keep shows me an error message)

[Package/Repository Information]
Repository URL     : https://pixinsight.deepskyforge.com/update/graxpert-process/
Signature          : <* unavailable *>
Authorized         : false
Available packages : 0
Selected packages  : 0
Error log:
https://pixinsight.deepskyforge.com/update/graxpert-process/: Network error: schannel: CertGetCertificateChain trust error CERT_TRUST_REVOCATION_STATUS_UNKNOWN

**Comment by DeepSkyForge** [comment]
Hello,

Message looks like a problem with my SSL certificat on [https://pixinsight.deepskyforge.com](https://pixinsight.deepskyforge.com/).
I checked my website and did not identified specif problem, SSL certificate is there.

I did a reset update in PixInsight 1.8.9-3 build 1611 and last build 1612 released today and no specific issue.
Process is loaded and installed without any issue.

Could you check again on your side?

Regards

**Comment by Nagant132017** [comment]
I have updated to Pixinsight 1.8.9-3 build 1612 today.
I went to the website "https://www.deepskyforge.com/index.html" and click the yellow link and ctrl+v to pixinsight 'RESOURCES > Updates > Manage Repositories'.
Then, when I click 'RESOURCES > Updates > Check for Updates', it still shows same signature error.

**Comment by Nagant132017** [comment]
Interestingly, I have also checked with my mac to find out whether it is okay.
With my mac, I've updated my pix to 1.8.9-3 build 1612, and all the scripts are updated very well.
I might think it could be the problem of Pixinsight or Window...

**Comment by DeepSkyForge** [comment]
I don't think it is related to PixInsight or Windows because it works for me, 80% of users run GraXpert on Windows and nobody reported similar issue.

I think it is more related to your Windows platform/environment.
What's your Windows version? Is it up to date?

If in PixInsight, you make a reset update, restart PixInsight, check update, update and restart PixInsight, does the problem occurs only with my module?

In PixInsight console, if you enter “lscpd”, do you see my certificate “JoelVallier”?

Does you PixInsight have a specific antivirus or firewall?

Last alternative could be to install manually the module and signature just to confirm that problem is only during download phase but I don’t know if you are familiar with this process.

**Comment by DeepSkyForge** [comment]
Could you take a look here:
https://pixinsight.com/forum/index.php?threads/fixed-network-error-schannel-certgetcertificatechain-trust-error.19691/

User reported similar issue with Windows/PixInsight.
Fresh windows install solved the issue.
You could start with an update.

People were suspecting antivirus also...

I hope this help...

**Comment by Nagant132017** [comment]
Thank you for responding me in detail.

1) I am using Windows 10. Since I'm on workplace, I would reply specific version when I get back to home.
2) I have already done 'Reset Update>restart Pixinsight>Check update>Update>restart Pixinsight', which shows same result.
3) I have found your certificate.
4) There is no antivirus or firewall.

**Comment by Nagant132017** [comment]
> Could you take a look here: https://pixinsight.com/forum/index.php?threads/fixed-network-error-schannel-certgetcertificatechain-trust-error.19691/
> 
> User reported similar issue with Windows/PixInsight. Fresh windows install solved the issue. You could start with an update.
> 
> People were suspecting antivirus also...
> 
> I hope this help...

Sad to hear that I have to install windows again...
I would do it and tell you the results soon.

**Comment by DeepSkyForge** [comment]
Another link:
https://www.rc-astro.com/faq/ssl-handshake-schannel-errors-in-pixinsight/

You should first ensure windows is up to date.
I don't know how you could clean-up certificates.

**Comment by Nagant132017** [comment]
Hello,

I have reinstall my window and it still does not work.
I have tried with another computer wich the Window 10 is installed and another Pixinsight account, and it still does not work.

I would try to use vpn since the only same thing with two computer is that those two are sharing the same internet port.

If there is any idea, let me know.

Thank you.

**Comment by Nagant132017** [comment]
Hi,

I am very happy to say that our network is blocking your site.
When I use vpn, it works well!
Sorry for bothering you.

Thank you.

**Comment by DeepSkyForge** [comment]
Thanks for your feedback!
