### ISSUE TITLE
Low-level API function error

### ISSUE THREAD

**Issue by AndyG88** [DeepSkyForge/GraXpert4PixInsight#35]
This is the result I get when running GraXpert in PI.

GraXpert: Processing view: Autosave
Image format: 32-bits floating sample
Writing image: w=1066 h=1825 n=3 RGB Float32
Mode background extraction
graxpert C:/Users/PC/AppData/Local/Temp/PixInsight.xisf -cli -smoothing 0.000 -correction Subtraction -bg

PixInsight API Error
StartExternalProcess(): Low-level API function error
365.034 ms

**Comment by DeepSkyForge** [comment]
Hi,

Normally GraXpert install process configure GraXpert path in system path.
See attached picture (sorry my screenshot in French).

![System-Path](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/157253452/1af49100-c62b-4c33-a07f-2ab17a2163dc)

Could you please check and add it if not yet the case.
You may have to restart window after the change (I'm not sure on this point).
When system path is properly configured, you can open a console (program "cmd") and enter "graxpert".
This should start GraXpert UI. 
If it's ok, it should work with the process. 

I'm preparing a new version where you will have the option to configure the path in GraXpert process.

Let me know if you need more help.

**Comment by DeepSkyForge** [comment]
Any news?
I'll release a new version this week-end where you will have the possibility to set path to GraXpert.
Regards,
Joël

**Comment by AndyG88** [comment]
Joel
Thanks for the follow up. The front end icon works in PI however it errors
once applied to an image ….” PI minor API error” is the message I get. I
will try the updated software once you’ve updated and let you know. (I’ll
also send the latest error message)

Cheers

Andrew

**Comment by DeepSkyForge** [comment]
Ok, I just released GraXpert process 2.1.0 where you can select path to GraXpert application.
If you still have a problem, you can activate "Show GraXpert logs" and copy/past PixInsight console logs here.
Regards,
Joël
