### ISSUE TITLE
Update error: "... Parsing Signature element (line=1 offset=0): Unknown code signing identity 'JoelVallier'"

### ISSUE THREAD

**Issue by SpaceFra** [DeepSkyForge/GraXpert4PixInsight#36]
i get this message, when PI tries to update:
https://pixinsight.deepskyforge.com/update/graxpert-process/: Parsing repository update information: Parsing Signature element (line=1 offset=0): Unknown code signing identity 'JoelVallier'

**Comment by DeepSkyForge** [comment]
Hi,

You'll find solution here:
https://github.com/DeepSkyForge/GraXpert4PixInsight/wiki/Unknow-code-signing-identity

Regards,

Joël
