### ISSUE TITLE
GraphXpert Suite n'apparait pas dans la liste des scripts dans Pixinsight

### ISSUE THREAD

**Issue by PascalB69** [DeepSkyForge/GraXpert4PixInsight#37]
Bonjour,

Je possède la version 1.8.9.3 Ripley (x64) (Build 1612) de Pixinsight 

et j'ai installé la version https://pixinsight.deepskyforge.com/update/graxpert-process/
Après installation, Graxpert est listé dans les "Resources Repositories" mais la suite n'apparait pas dans les scripts (?).

Avez-vous une solution ?

Merci d'avance.

**Comment by DeepSkyForge** [comment]
Bonsoir,
En fait il se trouve sous PROCESS > Etc > GraXpert et non sous le menu SCRIPT.
S'il n'est pas présent, un Reset Updates suivi d'un Check Updates devrait corriger le problème.
Sinon revenez vers moi.
Joël

**Comment by PascalB69** [comment]
Bonsoir Joël,
GraXpert n'était pas présent non plus sous PROCESS > Etc 
J'ai donc fait un Reset Updates suivi d'un Check Updates, et maintenant GraXpert est bien présent sous PROCESS > Etc
et semble fonctionner sur mes images.
Merci beaucoup pour votre aide !
Pascal
