### ISSUE TITLE
GraXpert4PixInsight not showing up in PixInsight Software

### ISSUE THREAD

**Issue by eposone1979** [DeepSkyForge/GraXpert4PixInsight#38]
![image](https://github.com/user-attachments/assets/0324fd95-5507-49ee-adc4-8ac4b5120e8e)

![image](https://github.com/user-attachments/assets/8d6c4bb7-a290-4040-96aa-42e56a6bce9a)

thanks much

**Comment by DeepSkyForge** [comment]
Sorry @eposone1979 for late answer.
Solution is described here: https://github.com/DeepSkyForge/GraXpert4PixInsight/wiki/GraXpert-not-installed
Let me know if it doesn't work for you.
Regards,
Joël

**Comment by eposone1979** [comment]
Thanks Joel
Will test it out
Cheers and clear skies

Sent from IPhone


DeepSkyForge ***@***.***> schrieb am Sa. 14. Sept. 2024 um
11:28:

**Comment by DeepSkyForge** [comment]
Hi, any news ?

**Comment by eposone1979** [comment]
It worked thanks

Sent from IPhone


DeepSkyForge ***@***.***> schrieb am Mi. 18. Sept. 2024 um
21:31:

**Comment by DeepSkyForge** [comment]
Thanks for your feedback.
