### ISSUE TITLE
Python error after update

### ISSUE THREAD

**Issue by yannsainty** [DeepSkyForge/GraXpert4PixInsight#39]
Hello,
I used to use the graXpert script but it didn't work anymore so I updated PixInsight and linked the new repository but I get this error:
![image](https://github.com/user-attachments/assets/0ae8fc72-b621-42dc-8371-9f354e31ed45)

Thanks for your help

**Comment by DeepSkyForge** [comment]
Hi,
Sorry for late answer.
I'm sure if you are using PixInsight Script (from menu Script) or Process (from menu Process > Etc).
If you can make a screenshot of script/process just for better clarity.

In any case, this is a known issue in GraXpert.
Please refer to this wiki: https://github.com/DeepSkyForge/GraXpert4PixInsight/wiki/AI-model-file-doesn't-exist

This should fix your issue whatever you use script or process..
Please confirm,

Regard,

Joël

**Comment by yannsainty** [comment]
Hello and thank you for your reply.

I had to launch the software first and then run a process to install the AI.

Thanks again.
