### ISSUE TITLE
Graxpert apply from PI get this error "PixInsight API Error StartExternalProcess(): Low-level API function error"

### ISSUE THREAD

**Issue by terrysilver420** [DeepSkyForge/GraXpert4PixInsight#40]
Installed GraXpert per https://www.deepskyforge.com/index.html , can launch app on my PC, but after etc/graxpert -  trying to apply from PI to image get "PixInsight API Error StartExternalProcess(): Low-level API function error"/  try to click launch from UI section of PI GraxPert window console shows "Launch GraXpert application:
Please wait...

Error
ExternalProcess: Failed to start process"

**Comment by DeepSkyForge** [comment]
Sorry for late answer.

Process try to launch GraXpert without specific path to the application and it fails.

You have to install GraXpert application. Refer documentation here: https://www.deepskyforge.com/documents/GraXpertProcess4PixInsight-EN.pdf.

It defauly path usually works on Windows and MacOSX as long as GraXpert is installed into default directory.
For Linux, most of the time you have to configure path using checkbox "Custom app. path".

Custom path works on Windows and MacOSX as well.
So check where GraXpert is installed and confirgure the path if needed.

Regards

**Comment by terrysilver420** [comment]
Thank you for reply - yes I had to tell it the path to install , then it
worked.

**Comment by DeepSkyForge** [comment]
Good!
