### ISSUE TITLE
Graxpert with Pix - API function error

### ISSUE THREAD

**Issue by Math0786** [DeepSkyForge/GraXpert4PixInsight#42]
Hi, 
I downloaded the  Pixinsight 1.9.2 Lockhart version because I couldn't install graxpert on version 1.8.2.
With the new version I was able to install graxpert but when I launch the module an error appears: "PixInsight API Error
StartExternalProcess(): API function error"

I tried removing the module updates and reinstalling them, I still have the same problem.

Thanks for your help.

**Comment by DeepSkyForge** [comment]
Hi,

Process try to launch GraXpert without specific path to the application and it fails.

You have to define path to GraXpert application. Refer documentation here: https://www.deepskyforge.com/documents/GraXpertProcess4PixInsight-EN.pdf.

Default path usually works on Windows and MacOSX as long as GraXpert is installed into default directory.
For Linux, most of the time you have to configure path using checkbox "Custom app. path".

Custom path works on Windows and MacOSX as well.
So check where GraXpert is installed and configure the path if needed.

Regards

**Comment by Math0786** [comment]
Thanks a lot it works :)
