### ISSUE TITLE
Error message at Icon load / strength slider value not reacting 

### ISSUE THREAD

**Issue by ggalb** [DeepSkyForge/GraXpert4PixInsight#5]
Hi there

I have encountered two problems:

1. When I load my process icons (the new GraXpert tool is in there) I receive 3 errors related to GraXpert and it takes PI more then 2 minutes to react. - How can I correct this from happening?
2. When I run the GraXpert Denoise tool with any strength below 1.0 - it still shows the used strength as being 1.0 - Is this an error in showing the wrong value or does the execution only run on strength 1.0 ???

Thank you very much - Georg

![Graxpert Icon load](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/167904304/018e2238-013e-419e-a1c4-16021198a93d)
![Graxpert Denoise strength](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/167904304/491967bb-2896-4849-80de-2d2ec89d74b6)

**Comment by DeepSkyForge** [comment]
Hi Georg,
Yes denoising takes several minutes.
You can stop process at any time by clicking on Pause/Abort button on console bottom right 

For the Strenght parameter, I'll copy/past explanations I shared on Discord Dark Matter ;-)

**Comment by DeepSkyForge** [comment]
Yes console show a call to GraXpert with Strenght 1.0 but result return by GraXpert is processed inside PixInsight to apply the Strength configured in the process dialog. I use exactly same formula defined in GraXpert: Result = denoised_image * strength + original_image * (1-strength). So at the end you have same result. If you don't trust me compare 2 processed images (one from GraXpert Application and another one from PixInsight process). I did it again with Strenght 0.5. Comparison is done with PixelMath and Statistics. See attached screenshot. M31 is the original photo, M31_GraXpert_05 is the denoised photo with GraXpert Application Strength 0.5, GraXpert_denoising is processed photo inside PixInsight with same Strength 0.5 (console show 1.0), Diff is PixelMath used to conpare each pixel processed (see formula in PixelMath). Then I used Process Statictics to see differences. All pixels are at 0.

![image](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/157253452/bf4ba24b-fadb-4ed1-bddc-91f9c1e8ca04)

**Comment by DeepSkyForge** [comment]
If you denoise same image with a different strength, result will be displayed withing less 2 seconds without any call to GraXper AI.
GraXpert Application use internally same principle.

**Comment by DeepSkyForge** [comment]
Point 1 is my top priority.
Dedicated case created: #8

**Comment by DeepSkyForge** [comment]
Hi ggalb,
Point 1 now fixed in version 2.0.2 just released.
Thanks for the report here and on Discord ;-)
Regards
