### ISSUE TITLE
Utilities GraXpert-All-in-One does not install

### ISSUE THREAD

**Issue by tim-moody** [DeepSkyForge/GraXpert4PixInsight#6]
I have installed GraXpert 3.0.0 in windows. It runs and I have downloaded the background and denoise AI models. (I actually removed the old version and reinstalled.)

I have updated resources in Pixinsight and Toolbox contains GraXpert and GraXpert Denoise. 

But Utilities does not contain  GraXpert-All-in-One. Also GraXpert Denoise says version 1.0 and requires 3.0.0, but GraXpert  still says version 1.4 and requires 2.2.0.

Any help appreciated.

**Comment by DeepSkyForge** [comment]
Sorry for delay, I was on travel.

Toolbox GraXpert and GraXpert Denoise is are differents scripts delievered here: https://www.ideviceapps.de/PixInsight/Utilities/
I cannot provide support.

GraXpert-All-in-One is replaced by GraXpert Process available here: https://www.deepskyforge.com/index.html
Process provide more feature that All-In-One :-)
Please install GraXpert Process and let me know if you need additional support.

**Comment by tim-moody** [comment]
Thanks. To be clear, both the Toolbox scripts and your process are wrappers for the graxpert executable?

**Comment by DeepSkyForge** [comment]
Yes both use GraXpert executable.
The difference are in the way we implemented the call to the executable and the features we provide.
But basicall, you'll get same result at the end in term of background extraction and denoising.

**Comment by tim-moody** [comment]
Thanks. Have just started using it, but no problems encountered so far.

**Comment by DeepSkyForge** [comment]
Ok thanks. I close the issue then.
